/**
 * =============================================================
 * AVATAR UPLOAD COMPONENT - File Upload with Preview
 * =============================================================
 *
 * Allows users to select an image file, preview it, and upload
 * it as their profile avatar.
 *
 * KEY CONCEPTS:
 *
 * 1. FILE INPUT:
 *    The <input type="file"> element lets users select files
 *    from their device. We use "accept" to limit to images.
 *    The actual input is hidden; we trigger it via a button click.
 *
 * 2. FILE READER API:
 *    FileReader reads a file's contents without uploading it.
 *    We use readAsDataURL() to get a base64 data URL that can
 *    be used as an <img> src for instant preview.
 *
 * 3. FORMDATA:
 *    FormData is the Web API for building multipart/form-data
 *    payloads (the format used for file uploads). We append
 *    the file with the field name 'avatar' to match what
 *    Multer expects on the server.
 *
 * 4. AXIOS WITH FORMDATA:
 *    When sending FormData, we set the Content-Type header to
 *    'multipart/form-data'. Axios auto-sets the boundary.
 *
 * UPLOAD FLOW:
 *    Select file -> Preview in browser -> Click Upload ->
 *    POST FormData to /api/users/avatar -> Update parent state
 *
 * PROPS:
 *   currentAvatarUrl - The user's current avatar URL (or null)
 *   onAvatarChange   - Callback with new avatar URL after upload
 * =============================================================
 */

import { useState, useRef } from 'react';
import apiClient from '../api/client';

function AvatarUpload({ currentAvatarUrl, onAvatarChange }) {
  // The selected file object (from the file input)
  const [selectedFile, setSelectedFile] = useState(null);

  // Data URL for image preview (generated by FileReader)
  const [previewUrl, setPreviewUrl] = useState(null);

  // UI state
  const [isUploading, setIsUploading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  // Ref to the hidden file input element
  // We use a ref to programmatically trigger the file dialog
  const fileInputRef = useRef(null);

  /**
   * Handle file selection from the file input.
   *
   * When a user selects a file, this handler:
   * 1. Validates the file type and size
   * 2. Creates a preview using FileReader
   * 3. Stores the file for later upload
   *
   * @param {Event} event - The change event from the file input
   */
  function handleFileSelect(event) {
    const file = event.target.files[0]; // Get the first (and only) selected file

    // Clear previous state
    setError('');
    setSuccess('');

    if (!file) {
      // User cancelled the file dialog
      setSelectedFile(null);
      setPreviewUrl(null);
      return;
    }

    // Client-side validation: file type
    const allowedTypes = ['image/jpeg', 'image/png', 'image/gif', 'image/webp'];
    if (!allowedTypes.includes(file.type)) {
      setError('Please select an image file (JPEG, PNG, GIF, or WebP)');
      return;
    }

    // Client-side validation: file size (5MB limit)
    const maxSize = 5 * 1024 * 1024; // 5MB in bytes
    if (file.size > maxSize) {
      setError('File is too large. Maximum size is 5MB.');
      return;
    }

    // Store the file for upload
    setSelectedFile(file);

    // Create a preview using FileReader
    // FileReader is a browser API that reads file contents asynchronously
    const reader = new FileReader();

    // This callback fires when reading is complete
    reader.onload = (e) => {
      // e.target.result is a data URL like:
      // "data:image/png;base64,iVBORw0KGgoAAAANS..."
      // This can be used directly as an <img> src
      setPreviewUrl(e.target.result);
    };

    // Start reading the file as a data URL (base64 encoded)
    reader.readAsDataURL(file);
  }

  /**
   * Upload the selected file to the server.
   *
   * Uses FormData to send the file as multipart/form-data.
   * The server (Multer) expects a field named 'avatar'.
   */
  async function handleUpload() {
    if (!selectedFile) {
      setError('Please select a file first');
      return;
    }

    setIsUploading(true);
    setError('');
    setSuccess('');

    try {
      // Create a FormData object and append the file
      // FormData automatically handles encoding for file uploads
      const formData = new FormData();
      formData.append('avatar', selectedFile); // 'avatar' matches upload.single('avatar') on server

      // POST the FormData to the upload endpoint
      // IMPORTANT: Set Content-Type to multipart/form-data
      // Axios will auto-set the correct boundary parameter
      const response = await apiClient.post('/api/users/avatar', formData, {
        headers: {
          'Content-Type': 'multipart/form-data',
        },
      });

      // Upload successful!
      setSuccess('Avatar uploaded successfully!');
      setSelectedFile(null);
      setPreviewUrl(null);

      // Notify the parent component of the new avatar URL
      if (onAvatarChange) {
        onAvatarChange(response.data.avatarUrl);
      }
    } catch (err) {
      const message =
        err.response?.data?.error || 'Failed to upload avatar. Please try again.';
      setError(message);
    } finally {
      setIsUploading(false);
    }
  }

  /**
   * Cancel the file selection and clear the preview.
   */
  function handleCancel() {
    setSelectedFile(null);
    setPreviewUrl(null);
    setError('');
    setSuccess('');
    // Reset the file input so the same file can be re-selected
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  }

  // Determine which image to display:
  // 1. Preview of newly selected file (before upload)
  // 2. Current avatar from the server
  // 3. Default placeholder
  const displayUrl = previewUrl || currentAvatarUrl || null;

  return (
    <div className="avatar-upload">
      {/* Avatar display */}
      <div className="avatar-display">
        {displayUrl ? (
          <img
            src={displayUrl}
            alt="User avatar"
            className="avatar-image"
          />
        ) : (
          // Default avatar placeholder (initials or generic icon)
          <div className="avatar-placeholder">
            <span>?</span>
          </div>
        )}
      </div>

      {/* Status messages */}
      {error && <div className="error-message avatar-error">{error}</div>}
      {success && <div className="success-message avatar-success">{success}</div>}

      {/* File input - hidden, triggered by button click */}
      <input
        ref={fileInputRef}
        type="file"
        accept="image/jpeg,image/png,image/gif,image/webp"
        onChange={handleFileSelect}
        className="avatar-file-input"
        style={{ display: 'none' }} // Hidden - triggered via ref
      />

      {/* Action buttons */}
      <div className="avatar-actions">
        {selectedFile ? (
          // File selected - show upload and cancel buttons
          <>
            <button
              onClick={handleUpload}
              className="btn btn-primary"
              disabled={isUploading}
            >
              {isUploading ? 'Uploading...' : 'Upload Avatar'}
            </button>
            <button
              onClick={handleCancel}
              className="btn btn-cancel"
              disabled={isUploading}
            >
              Cancel
            </button>
          </>
        ) : (
          // No file selected - show choose file button
          <button
            onClick={() => fileInputRef.current?.click()}
            className="btn btn-primary"
          >
            {currentAvatarUrl ? 'Change Avatar' : 'Upload Avatar'}
          </button>
        )}
      </div>

      {/* File info display */}
      {selectedFile && (
        <p className="avatar-file-info">
          Selected: {selectedFile.name} ({(selectedFile.size / 1024).toFixed(1)} KB)
        </p>
      )}
    </div>
  );
}

export default AvatarUpload;
